---
title: "Flexdashboard Code"
author: "Tvisha R. Devavarapu"
date: "2022-10-31"
output: html_document
---

# Set-up
```{r}
library(tidyverse)

library(plotly)
```

```{r}
library(p8105.datasets)
data("instacart")

instacart_df =
  instacart %>%
    janitor::clean_names()
```


#1 Most ordered fresh vegetables

```{r Most ordered fresh veggies}
instacart_df %>% 
  select(product_name, aisle) %>% 
  filter(aisle == "fresh vegetables") %>% 
  group_by(product_name) %>% 
  summarise(counts = n()) %>% 
  filter(counts > 1000) %>% 
  mutate(product_name = fct_reorder(product_name, counts)) %>% 
  plot_ly(x = ~product_name, y = ~counts, type = "bar")
  
```

#2 Time-wise trend in overall produce/snacks/personal-care orders

```{r Time-wise trend in overall produce/snacks/personal-care orders}
instacart_df %>% 
  select(order_hour_of_day, department) %>% 
  mutate(order_hour_of_day = factor(order_hour_of_day)) %>% 
  filter(department %in% c("produce", "snacks", "personal care")) %>% 
  group_by(order_hour_of_day, department) %>% 
  summarise(counts = n()) %>% 
  plot_ly(x = ~order_hour_of_day, y = ~counts,
          type = "scatter", mode = "markers",
          color = ~department, size = ~counts,
          text = ~paste("Time: ", order_hour_of_day, "/24", '<br>Counts:', counts))
```

#3 Top 5 items in Top 10 Aisles

```{r Top 5 items in Top 10 Aisles - rank as factor ver.}
aisle_counts = 
  instacart_df %>% 
    group_by(aisle) %>% 
    count(aisle) %>%
    arrange(desc(n))

top_10_aisles = aisle_counts$aisle[1:10]

instacart_df %>% 
  filter(aisle %in% top_10_aisles) %>% 
  group_by(aisle) %>% 
  count(product_name) %>% 
  mutate(rank = min_rank(desc(n))) %>% 
  filter(rank < 6) %>% 
  mutate(rank = factor(rank)) %>% 
  arrange(aisle, rank) %>% 
  plot_ly(x = ~aisle, y = ~n, type = "bar", color = ~rank,
          text = ~paste("Name: ", product_name, '<br>Counts:', n))
```

